version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: massbank_mariadb
    volumes:
      - /mariadb:/var/lib/mysql
      - $PWD/modules/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123blah321
    restart: always
  tomcat:
    image: tomcat:latest
    container_name: massbank_tomcat
    volumes:
      - $PWD/MassBank-Project/MassBank/target/MassBank.war:/usr/local/tomcat/webapps/MassBank.war
      - $PWD/massbank.conf:/etc/massbank.conf
    ports:
      - '8080:8080'
    restart: always
