dependencies:
  - name: mariadb
    version: 5.2.3
    repository: https://massbank.github.io/MassBank-web
  - name: tomcat
    version: 0.1.0
    repository: https://massbank.github.io/MassBank-web
    