version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: massbank_mariadb
    volumes:
      - /mariadb:/var/lib/mysql
      - $PWD/modules/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        #    ports:
        #- '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123blah321
    restart: always
  tomcat:
    image: tomcat:latest
    container_name: massbank_tomcat
    volumes:
      - $PWD/MassBank-Project/MassBank/target/MassBank.war:/usr/local/tomcat/webapps/MassBank.war
      - $PWD/conf/full-service.conf:/etc/massbank.conf
      - $PWD/../MassBank-data:/MassBank-data  
    ports:
      - '80:8080'
    restart: always
  maven:
    image: maven:latest
    container_name: massbank_maven
    volumes:
      - $HOME/.m2:/root/.m2
      - $PWD/MassBank-Project:/project
      - $PWD/conf/full-service.conf:/etc/massbank.conf
      - $PWD/../MassBank-data:/MassBank-data
